/*
THIS IS A GENERATED BUNDLE FOR OBSIDIAN PLUGIN.
DO NOT EDIT THIS FILE DIRECTLY.
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HEExtPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE = "html-effectiveness-view";
var DEFAULT_SETTINGS = { defaultTheme: "dark" };
function escapeHtml(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
function applyMd(parent, text) {
  const lines = text.split("\n");
  let i = 0;
  while (i < lines.length) {
    const line = lines[i];
    if (line.trimStart().startsWith("```")) {
      const lang = line.trimStart().slice(3).trim();
      const codeLines = [];
      i++;
      while (i < lines.length && !lines[i].trimStart().startsWith("```")) {
        codeLines.push(lines[i]);
        i++;
      }
      i++;
      const pre = parent.createEl("pre");
      const code = pre.createEl("code");
      if (lang)
        code.addClass("language-" + lang);
      code.textContent = codeLines.join("\n");
      continue;
    }
    if (line.trimStart().startsWith("> ")) {
      const bq = parent.createEl("blockquote");
      const quoteLines = [];
      while (i < lines.length && lines[i].trimStart().startsWith("> ")) {
        quoteLines.push(lines[i].trimStart().slice(2));
        i++;
      }
      applyInline(bq, quoteLines.join("\n"));
      continue;
    }
    if (line.trimStart().match(/^[-*]\s/)) {
      const ul = parent.createEl("ul");
      while (i < lines.length && lines[i].trimStart().match(/^[-*]\s/)) {
        const li = ul.createEl("li");
        applyInline(li, lines[i].trimStart().slice(2));
        i++;
      }
      continue;
    }
    if (line.trimStart().match(/^\d+\.\s/)) {
      const ol = parent.createEl("ol");
      while (i < lines.length && lines[i].trimStart().match(/^\d+\.\s/)) {
        const li = ol.createEl("li");
        applyInline(li, lines[i].trimStart().replace(/^\d+\.\s*/, ""));
        i++;
      }
      continue;
    }
    const headingMatch = line.match(/^(#{1,6})\s+(.+)/);
    if (headingMatch) {
      const level = Math.min(headingMatch[1].length, 6);
      const h = parent.createEl("h" + level);
      applyInline(h, headingMatch[2]);
      i++;
      continue;
    }
    if (line.match(/^---+\s*$/)) {
      parent.createEl("hr");
      i++;
      continue;
    }
    if (line.trim() === "") {
      i++;
      continue;
    }
    const p = parent.createEl("p");
    applyInline(p, line);
    i++;
  }
}
function applyInline(parent, text) {
  const escaped = text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  const parts = [];
  let lastIndex = 0;
  let match;
  const regex = /(\*\*[^*]+\*\*|__[^_]+__|\*[^*]+\*|_[^_]+_|`[^`]+`|~~[^~]+~~|!\[([^\]]*)\]\(([^)]+)\)|\[([^\]]+)\]\(([^)]+)\))/g;
  while ((match = regex.exec(escaped)) !== null) {
    if (match.index > lastIndex) {
      parts.push({ type: "text", content: escaped.slice(lastIndex, match.index) });
    }
    const full = match[0];
    if (full.startsWith("**") || full.startsWith("__")) {
      parts.push({ type: "bold", content: full.slice(2, -2) });
    } else if (full.startsWith("*") && !full.startsWith("**")) {
      parts.push({ type: "italic", content: full.slice(1, -1) });
    } else if (full.startsWith("_") && !full.startsWith("__")) {
      parts.push({ type: "italic", content: full.slice(1, -1) });
    } else if (full.startsWith("`")) {
      parts.push({ type: "code", content: full.slice(1, -1) });
    } else if (full.startsWith("~~")) {
      parts.push({ type: "del", content: full.slice(2, -2) });
    } else if (full.startsWith("![")) {
      const alt = match[2] || "";
      const src = match[3] || "";
      parts.push({ type: "image", content: JSON.stringify({ alt, src }) });
    } else if (full.startsWith("[")) {
      const linkText = match[4] || full.slice(1, full.indexOf("]"));
      const url = match[5] || "";
      parts.push({ type: "link", content: JSON.stringify({ text: linkText, url }) });
    }
    lastIndex = match.index + full.length;
  }
  if (lastIndex < escaped.length) {
    parts.push({ type: "text", content: escaped.slice(lastIndex) });
  }
  if (parts.length === 0) {
    parent.appendChild(document.createTextNode(escaped));
    return;
  }
  for (const part of parts) {
    switch (part.type) {
      case "text":
        parent.appendChild(document.createTextNode(part.content));
        break;
      case "bold":
        parent.createEl("strong", { text: part.content });
        break;
      case "italic":
        parent.createEl("em", { text: part.content });
        break;
      case "code":
        parent.createEl("code", { cls: "he-inline-code", text: part.content });
        break;
      case "del":
        parent.createEl("del", { text: part.content });
        break;
      case "link": {
        const data = JSON.parse(part.content);
        parent.createEl("a", { text: data.text, href: data.url });
        break;
      }
      case "image": {
        const data = JSON.parse(part.content);
        parent.createEl("img", { attr: { src: data.src, alt: data.alt } });
        break;
      }
    }
  }
}
function buildCompare(parent, content, theme) {
  const outer = parent.createDiv({ cls: "he-compare " + theme });
  const cols = [];
  let cur = null;
  let nextTag = "";
  const lines = content.split("\n");
  let i = 0;
  function flush() {
    if (cur && (cur.title || cur.bodyLines.length > 0 || cur.codeBlock || cur.pros.length > 0 || cur.cons.length > 0 || cur.metrics.length > 0)) {
      cols.push(cur);
    }
  }
  while (i < lines.length) {
    const line = lines[i];
    const tagSep = line.match(/^---tag:\s*(.+)/);
    if (tagSep) {
      flush();
      nextTag = tagSep[1];
      cur = null;
      i++;
      continue;
    }
    if (/^---+\s*$/.test(line)) {
      flush();
      cur = null;
      i++;
      continue;
    }
    if (!cur) {
      cur = { tag: nextTag, title: "", codeBlock: null, pros: [], cons: [], metrics: [], bodyLines: [] };
      nextTag = "";
    }
    const tm = line.match(/^#\s+(.+)/);
    if (tm && !cur.title) {
      cur.title = tm[1];
      i++;
      continue;
    }
    if (/^```/.test(line)) {
      const lang = line.replace(/^```/, "").trim();
      const codeLines = [];
      i++;
      while (i < lines.length && !/^```/.test(lines[i])) {
        codeLines.push(lines[i]);
        i++;
      }
      i++;
      cur.codeBlock = { lang, code: codeLines.join("\n") };
      continue;
    }
    if (/^###\s+Metrics\s*$/i.test(line)) {
      i++;
      while (i < lines.length && lines[i].trim() !== "" && !/^---/.test(lines[i]) && !/^#{1,3}\s/.test(lines[i]) && !/^```/.test(lines[i])) {
        cur.metrics.push(lines[i]);
        i++;
      }
      continue;
    }
    if (/^\|.*\|\s*$/.test(line) && /Pro/i.test(line) && /Con/i.test(line)) {
      i++;
      if (i < lines.length && /^\|[\s:-]+\|/.test(lines[i]))
        i++;
      while (i < lines.length && /^\|.*\|\s*$/.test(lines[i])) {
        const parts = lines[i].split("|").filter((c) => c.trim() !== "").map((c) => c.trim());
        if (parts.length >= 2) {
          cur.pros.push(parts[0]);
          cur.cons.push(parts[1]);
        } else if (parts.length === 1) {
          cur.pros.push(parts[0]);
          cur.cons.push("");
        }
        i++;
      }
      continue;
    }
    cur.bodyLines.push(line);
    i++;
  }
  flush();
  let recommendation = null;
  if (cols.length > 0) {
    const last = cols[cols.length - 1];
    const bodyJoined = last.bodyLines.join("\n");
    const recMatch = bodyJoined.match(/^##\s+(?:Recommendation|建议):?\s*\n([\s\S]*)$/);
    if (recMatch) {
      recommendation = recMatch[1].trim();
      cols.pop();
    } else {
      const recInline = bodyJoined.match(/##\s+(?:Recommendation|建议):?\s*\n([\s\S]*)$/);
      if (recInline) {
        recommendation = recInline[1].trim();
        const beforeRec = bodyJoined.replace(/##\s+(?:Recommendation|建议):?\s*\n[\s\S]*$/, "").trim();
        last.bodyLines = beforeRec ? beforeRec.split("\n") : [];
      }
    }
  }
  for (const col of cols) {
    const card = outer.createDiv({ cls: "he-approach" });
    const header = card.createDiv({ cls: "he-approach-header" });
    if (col.tag) {
      header.createSpan({ cls: "he-tag", text: escapeHtml(col.tag) });
    }
    if (col.title) {
      header.createEl("h2", { cls: "he-approach-title", text: escapeHtml(col.title) });
    }
    if (col.codeBlock) {
      const pre = card.createEl("pre", { cls: "he-approach-code" });
      const code = pre.createEl("code");
      if (col.codeBlock.lang)
        code.addClass("language-" + col.codeBlock.lang);
      code.textContent = col.codeBlock.code;
    }
    if (col.pros.length > 0 || col.cons.length > 0) {
      const table = card.createEl("table", { cls: "he-proscons" });
      const thead = table.createEl("thead");
      const hr = thead.createEl("tr");
      hr.createEl("th", { text: "Pro" });
      hr.createEl("th", { text: "Con" });
      const tbody = table.createEl("tbody");
      const maxRows = Math.max(col.pros.length, col.cons.length);
      for (let r = 0; r < maxRows; r++) {
        const tr = tbody.createEl("tr");
        tr.createEl("td", { text: escapeHtml(col.pros[r] || "") });
        tr.createEl("td", { text: escapeHtml(col.cons[r] || "") });
      }
    }
    if (col.bodyLines.length > 0) {
      const bodyDiv = card.createDiv({ cls: "he-approach-body" });
      applyMd(bodyDiv, col.bodyLines.join("\n"));
    }
    if (col.metrics.length > 0) {
      const footer = card.createEl("footer", { cls: "he-metrics" });
      for (const mLine of col.metrics) {
        const span = footer.createEl("span");
        applyInline(span, mLine);
      }
    }
  }
  if (recommendation) {
    const banner = outer.createDiv({ cls: "he-recommendation" });
    banner.createEl("strong", { text: "\u5EFA\u8BAE\uFF1A" });
    banner.appendChild(document.createTextNode(" "));
    applyInline(banner, recommendation);
  }
}
function buildTimeline(parent, content) {
  const ul = parent.createEl("ul", { cls: "he-timeline" });
  const items = content.trim().split("\n").filter((l) => l.trim());
  for (const line of items) {
    const li = ul.createEl("li", { cls: "he-tl-item" });
    let body = line.replace(/^-\s+/, "");
    let dateStr = null;
    const dateMatch = body.match(/^\[(.+?)\]\s*/);
    if (dateMatch) {
      dateStr = dateMatch[1];
      body = body.slice(dateMatch[0].length);
    }
    let sev = null;
    const sevMatch = body.match(/\s*\[sev:(high|med|low)\]\s*$/i);
    if (sevMatch) {
      body = body.slice(0, sevMatch.index);
      sev = sevMatch[1].toLowerCase();
    }
    if (dateStr) {
      li.createSpan({ cls: "he-tl-date", text: dateStr });
    }
    const textSpan = li.createSpan({ cls: "he-tl-text" });
    applyMd(textSpan, body);
    if (sev) {
      li.createSpan({ cls: "he-tl-sev " + sev, text: sev.charAt(0).toUpperCase() + sev.slice(1) });
      li.classList.add("sev-" + sev);
    }
  }
}
function buildDiagram(parent, content) {
  const d = parent.createDiv({ cls: "he-diagram" });
  const lines = content.split("\n");
  const hasBoxArrow = lines.some((l) => /^\s*[[({\u250c\u2502\u2514]/.test(l.trim()));
  if (!hasBoxArrow) {
    d.createEl("pre", { cls: "he-diagram-pre", text: escapeHtml(content) });
    return;
  }
  const NODE_H = 56;
  const GAP_X = 40;
  const GAP_Y = 80;
  const PAD = 24;
  const nodes = [];
  const rowCols = [];
  for (const raw of lines) {
    const line = raw.trimEnd();
    if (!line)
      continue;
    const indent = raw.length - raw.trimStart().length;
    const row = Math.round(indent / 2);
    const pushNode = (text, type) => {
      const col = rowCols[row] ?? 0;
      rowCols[row] = col + 1;
      const w = Math.max(120, Math.min(text.length * 7.2 + 30, 300));
      nodes.push({ text, type, row, col, w, x: 0, y: 0 });
    };
    const pm = /^\[([^\]]+)\]/.exec(line);
    if (pm) {
      pushNode(pm[1], "process");
      continue;
    }
    const tm = /^\(([^)]+)\)/.exec(line);
    if (tm) {
      pushNode(tm[1], "terminal");
      continue;
    }
    const dm = /^\{([^}]+)\}/.exec(line);
    if (dm) {
      pushNode(dm[1], "decision");
      continue;
    }
  }
  if (nodes.length === 0) {
    d.createEl("pre", { cls: "he-diagram-pre", text: escapeHtml(content) });
    return;
  }
  for (const n of nodes) {
    const sameRow = nodes.filter((o) => o.row === n.row).sort((a, b) => a.col - b.col);
    let x = PAD;
    for (const rn of sameRow) {
      if (rn.col < n.col)
        x += rn.w + GAP_X;
    }
    n.x = x;
    n.y = n.row * (NODE_H + GAP_Y) + PAD;
  }
  const svgW = Math.max(...nodes.map((n) => n.x + n.w + PAD), 200);
  const svgH = Math.max(...nodes.map((n) => n.y + NODE_H + PAD), 100);
  const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  let svg = `<svg viewBox="0 0 ${svgW} ${svgH}" xmlns="http://www.w3.org/2000/svg">
<defs>
  <marker id="arr" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
    <path d="M 0 0 L 10 5 L 0 10 z" fill="#141413"/>
  </marker>
</defs>
`;
  for (const n of nodes) {
    const next = nodes.find((o) => o.row === n.row && o.col === n.col + 1);
    if (!next)
      continue;
    svg += `<path class="edge" d="M ${n.x + n.w} ${n.y + NODE_H / 2} L ${next.x} ${next.y + NODE_H / 2}" marker-end="url(#arr)"/>
`;
  }
  for (const n of nodes) {
    const below = nodes.find((o) => o.row === n.row + 1 && o.col === n.col);
    if (!below)
      continue;
    const x1 = n.x + n.w / 2;
    const y1 = n.y + NODE_H;
    const x2 = below.x + below.w / 2;
    const y2 = below.y;
    if (Math.abs(x1 - x2) > 2) {
      const my = (y1 + y2) / 2;
      svg += `<path class="edge" d="M ${x1} ${y1} L ${x1} ${my} L ${x2} ${my} L ${x2} ${y2}" marker-end="url(#arr)"/>
`;
    } else {
      svg += `<path class="edge" d="M ${x1} ${y1} L ${x2} ${y2}" marker-end="url(#arr)"/>
`;
    }
  }
  for (const n of nodes) {
    const cx = n.x + n.w / 2;
    const cy = n.y + NODE_H / 2;
    const label = esc(n.text);
    switch (n.type) {
      case "process":
        svg += `<rect x="${n.x}" y="${n.y}" width="${n.w}" height="${NODE_H}" rx="8" class="node-bg"/>
`;
        break;
      case "terminal":
        svg += `<rect x="${n.x}" y="${n.y}" width="${n.w}" height="${NODE_H}" rx="${NODE_H / 2}" class="node-bg"/>
`;
        break;
      case "decision":
        svg += `<polygon points="${cx},${n.y} ${n.x + n.w},${cy} ${cx},${n.y + NODE_H} ${n.x},${cy}" class="node-bg"/>
`;
        break;
    }
    svg += `<text x="${cx}" y="${cy}" class="node-label" text-anchor="middle" dominant-baseline="central">${label}</text>
`;
  }
  svg += `</svg>`;
  d.insertAdjacentHTML("afterbegin", svg);
  const leg = d.createDiv({ cls: "he-diagram-caption" });
  function legItem(shape, label) {
    const span = leg.createSpan({ attr: { style: "display:inline-flex;align-items:center;gap:4px;margin:0 8px;" } });
    const swatch = span.createSpan({ attr: { style: "display:inline-block;border:1.5px solid var(--he-gray-500,#87867F);background:var(--he-gray-100,#F0EEE6);vertical-align:middle;" + shape } });
    span.appendText(" " + label);
  }
  legItem("width:20px;height:8px;border-radius:3px;", "process");
  legItem("width:20px;height:8px;border-radius:4px;", "terminal");
  legItem("width:8px;height:8px;transform:rotate(45deg);", "decision");
}
function buildReport(parent, content, theme) {
  const outer = parent.createDiv({ cls: "he-report " + theme });
  const lines = content.trim().split("\n");
  let section = "none";
  let kpiRow = null;
  let highlightsUl = null;
  let shippedThead = null;
  let shippedTbody = null;
  let shippedFirstRow = true;
  let velocityChart = null;
  let carryoverDiv = null;
  const bodyDiv = outer.createDiv({ cls: "he-report-body" });
  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line)
      continue;
    if (line.startsWith("## ")) {
      const title = line.slice(3).trim();
      if (title === "" || title === "KPI") {
        section = "kpi";
        kpiRow = outer.createDiv({ cls: "he-kpi-row" });
        continue;
      }
      bodyDiv.createEl("h4", { cls: "he-report-h3", text: escapeHtml(title) });
      continue;
    }
    const h1Match = line.match(/^#\s+(.+)/);
    if (h1Match) {
      const title = h1Match[1];
      section = "body";
      shippedFirstRow = true;
      switch (title) {
        case "Highlights": {
          section = "highlights";
          const hlSec = outer.createDiv({ cls: "he-highlights" });
          highlightsUl = hlSec.createEl("ul");
          break;
        }
        case "Shipped": {
          section = "shipped";
          const tbl = outer.createEl("table", { cls: "he-shipped" });
          shippedThead = tbl.createEl("thead");
          shippedTbody = tbl.createEl("tbody");
          break;
        }
        case "Velocity": {
          section = "velocity";
          const velSec = outer.createDiv({ cls: "he-velocity" });
          velocityChart = velSec.createDiv({ cls: "chart" });
          break;
        }
        case "Carryover": {
          section = "carryover";
          carryoverDiv = outer.createDiv({ cls: "he-carryover" });
          break;
        }
        default:
          bodyDiv.createEl("h3", { cls: "he-report-h3", text: escapeHtml(title) });
          break;
      }
      continue;
    }
    switch (section) {
      case "kpi": {
        if (!kpiRow)
          break;
        const km = line.match(/^-\s*(\d+(?:\.\d+)?[%MBTk]?)\s*:\s*(.+?)(?:\s*\(delta:\s*([+-]?±?\d+(?:\.\d+)?[%MBTk]?)\))?\s*$/);
        if (km) {
          const k = kpiRow.createDiv({ cls: "he-kpi" });
          k.createDiv({ cls: "he-kpi-num", text: escapeHtml(km[1]) });
          k.createDiv({ cls: "he-kpi-label", text: escapeHtml(km[2]) });
          if (km[3]) {
            const d = km[3];
            const dc = d.startsWith("+") ? " up" : d.startsWith("-") ? " down" : "";
            k.createDiv({ cls: "he-kpi-delta" + dc, text: escapeHtml(d) });
          }
        }
        break;
      }
      case "highlights": {
        if (!highlightsUl)
          break;
        const hm = line.match(/^-\s+(.+)/);
        if (hm) {
          const li = highlightsUl.createEl("li");
          applyInline(li, hm[1]);
        }
        break;
      }
      case "shipped": {
        if (!line.startsWith("|"))
          break;
        if (shippedFirstRow && shippedThead) {
          const tr = shippedThead.createEl("tr");
          line.split("|").filter(Boolean).forEach(
            (c) => tr.createEl("th", { text: escapeHtml(c.trim()) })
          );
          shippedFirstRow = false;
        } else if (shippedTbody) {
          const tr = shippedTbody.createEl("tr");
          const cells = line.split("|").filter(Boolean).map((c) => c.trim());
          cells.forEach((c, i) => {
            const td = tr.createEl("td");
            if (i === cells.length - 1 && /^(low|med|high)$/i.test(c)) {
              td.createSpan({ cls: "he-risk-pill " + c.toLowerCase(), text: escapeHtml(c) });
            } else {
              td.textContent = c;
            }
          });
        }
        break;
      }
      case "velocity": {
        if (!velocityChart)
          break;
        const parts = line.split(",").map((s) => s.trim());
        const entries = [];
        let maxVal = 0;
        for (const part of parts) {
          const vm = part.match(/^([A-Za-z]+):(\d+(?:\.\d+)?)/);
          if (vm) {
            const v = parseFloat(vm[2]);
            entries.push({ day: vm[1], val: v });
            if (v > maxVal)
              maxVal = v;
          }
        }
        if (entries.length === 0)
          break;
        const scale = maxVal || 1;
        for (const { day, val } of entries) {
          const bar = velocityChart.createDiv({ cls: "bar" });
          const col = bar.createDiv({ cls: "col" });
          col.style.height = val / scale * 100 + "%";
          col.setAttribute("data-v", String(val));
          bar.createEl("small", { text: day });
        }
        break;
      }
      case "carryover": {
        if (!carryoverDiv)
          break;
        const cm = line.match(/^-\s*\[(.+?)\]\s*(.+)/);
        if (cm) {
          const status = cm[1].toLowerCase();
          const desc = cm[2];
          const item = carryoverDiv.createDiv({ cls: "item " + status });
          item.createSpan({ cls: "label", text: escapeHtml(status) });
          const descSpan = item.createSpan({ cls: "desc" });
          applyInline(descSpan, desc);
        }
        break;
      }
      default: {
        const p = bodyDiv.createEl("p");
        applyInline(p, line);
        break;
      }
    }
  }
}
function buildSlides(parent, content) {
  const slides = content.split("\n---\n").filter(Boolean);
  const slideDivs = [];
  let currentIdx = 0;
  const nav = parent.createDiv({ cls: "he-slides-nav" });
  nav.createEl("button", { text: chr(9664), cls: "he-slide-btn" }).addEventListener("click", () => {
    if (currentIdx > 0)
      showSlide(currentIdx - 1);
  });
  const counter = nav.createSpan({ cls: "he-slide-counter" });
  nav.createEl("button", { text: chr(9654), cls: "he-slide-btn" }).addEventListener("click", () => {
    if (currentIdx < slideDivs.length - 1)
      showSlide(currentIdx + 1);
  });
  const wrap = parent.createDiv({ cls: "he-slides" });
  wrap.setAttribute("tabindex", "0");
  function showSlide(idx) {
    slideDivs.forEach((s, i) => s.classList.toggle("he-slide-hidden", i !== idx));
    counter.textContent = idx + 1 + " / " + slideDivs.length;
    currentIdx = idx;
  }
  const keyHandler = (e) => {
    if (e.key === "ArrowRight" || e.key === " " || e.key === "PageDown") {
      e.preventDefault();
      if (currentIdx < slideDivs.length - 1)
        showSlide(currentIdx + 1);
    } else if (e.key === "ArrowLeft" || e.key === "PageUp") {
      e.preventDefault();
      if (currentIdx > 0)
        showSlide(currentIdx - 1);
    } else if (e.key === "Home" || e.key === ".") {
      e.preventDefault();
      showSlide(0);
    } else if (e.key === "End") {
      e.preventDefault();
      showSlide(slideDivs.length - 1);
    } else if (e.key === "f") {
      e.preventDefault();
      if (!document.fullscreenElement) {
        document.documentElement.requestFullscreen().catch(() => {
        });
      } else {
        document.exitFullscreen().catch(() => {
        });
      }
    }
  };
  parent.addEventListener("keydown", keyHandler);
  for (let i = 0; i < slides.length; i++) {
    const lines = slides[i].trim().split("\n");
    const title = lines.shift()?.replace(/^#\s*/, "") || "";
    const sd = wrap.createDiv({ cls: "he-slide", attr: { "data-index": String(i) } });
    if (i > 0)
      sd.classList.add("he-slide-hidden");
    sd.createEl("h2", { cls: "he-slide-title", text: escapeHtml(title) });
    const sb = sd.createDiv({ cls: "he-slide-body" });
    applyMd(sb, lines.join("\n"));
    slideDivs.push(sd);
  }
  showSlide(0);
  const help = parent.createDiv({ cls: "he-slides-help" });
  help.createSpan({ text: "\u2190 \u2192 or Space: navigate \xB7 f: fullscreen \xB7 Home/End: first/last" });
}
function chr(c) {
  return String.fromCharCode(c);
}
function processor(source, el, _ctx, defaultTheme) {
  let type = "report";
  let theme = defaultTheme === "light" ? "light" : "dark";
  let content = source;
  const nl = source.indexOf("\n");
  if (nl > 0) {
    const fl = source.substring(0, nl).trim();
    if (fl.startsWith("---")) {
      const end = source.indexOf("---", 3);
      if (end > 0) {
        const yml = source.substring(3, end).trim();
        try {
          const parsed = (0, import_obsidian.parseYaml)(yml);
          if (parsed && typeof parsed === "object") {
            const o = parsed;
            if (o.theme === "light")
              theme = "light";
            if (typeof o.type === "string") {
              const t = o.type;
              if (t === "compare" || t === "timeline" || t === "diagram" || t === "report" || t === "slides")
                type = t;
            }
          }
        } catch {
        }
        content = source.substring(end + 3).trim();
      }
    } else {
      const t = fl.toLowerCase();
      if (t === "compare" || t === "timeline" || t === "diagram" || t === "report" || t === "slides") {
        type = t;
        content = source.substring(nl + 1).trim();
      }
    }
  }
  const w = el.createDiv({ cls: "he-wrapper " + theme });
  switch (type) {
    case "compare":
      buildCompare(w, content, theme);
      break;
    case "timeline":
      buildTimeline(w, content);
      break;
    case "diagram":
      buildDiagram(w, content);
      break;
    case "report":
      buildReport(w, content, theme);
      break;
    case "slides":
      buildSlides(w, content);
      break;
  }
}
async function exportNoteAsHTML(app, plugin) {
  const file = app.workspace.getActiveFile();
  if (!file) {
    new import_obsidian.Notice("No active note");
    return;
  }
  const content = await app.vault.read(file);
  const tempEl = createDiv();
  await import_obsidian.MarkdownRenderer.render(app, content, tempEl, file.path, plugin);
  const bodyHtml = tempEl.innerHTML;
  const title = file.basename;
  const htmlDoc = buildStandaloneHtml(bodyHtml, title);
  const outPath = (file.parent ? file.parent.path + "/" : "") + title + ".html";
  await app.vault.create(outPath, htmlDoc);
  new import_obsidian.Notice("Exported: " + outPath);
}
function buildStandaloneHtml(bodyHtml, title) {
  return `<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(title)}</title>
<style>
:root {
  --he-clay: #D97757; --he-slate: #141413; --he-ivory: #FAF9F5; --he-oat: #E3DACC;
  --he-white: #FFFFFF; --he-gray-100: #F0EEE6; --he-gray-300: #D1CFC5;
  --he-gray-500: #87867F; --he-gray-700: #3D3D3A;
  --he-success: #788C5D; --he-warning: #C78E3F; --he-danger: #B04A4A; --he-info: #5C7CA3;
  --he-font-sans: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
  --he-font-mono: ui-monospace, "SF Mono", Menlo, Monaco, Consolas, "Liberation Mono", monospace;
}
body { font-family: var(--he-font-sans); font-size: 16px; line-height: 1.6;
       color: var(--he-slate); background: var(--he-ivory); max-width: 880px;
       margin: 0 auto; padding: 48px 24px; -webkit-font-smoothing: antialiased; }
h1 { font-size: 28px; font-weight: 500; }
h2 { font-size: 22px; font-weight: 500; }
h3 { font-size: 18px; font-weight: 500; }
code { font-family: var(--he-font-mono); font-size: 0.9em; background: var(--he-gray-100); padding: 2px 6px; border-radius: 4px; }
pre { background: var(--he-gray-100); padding: 16px; border-radius: 8px; overflow: auto; }
pre code { background: none; padding: 0; }
a { color: var(--he-info); text-decoration: none; border-bottom: 1px solid currentColor; }
blockquote { border-left: 3px solid var(--he-gray-300); margin: 0; padding: 8px 20px; color: var(--he-gray-700); }
table { width: 100%; border-collapse: collapse; }
th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid var(--he-gray-300); }
img { max-width: 100%; }
.zoom-container { transform-origin: top left; }
.zoom-bar { position: fixed; bottom: 24px; right: 24px; display: flex; align-items: center; gap: 4px; padding: 4px 8px; background: var(--he-white); border: 1px solid var(--he-gray-300); border-radius: 12px; box-shadow: 0 4px 10px rgba(20,20,19,.08); z-index: 999; user-select: none; opacity: .7; transition: opacity .2s; }
.zoom-bar:hover { opacity: 1; }
.zoom-btn { display: grid; place-items: center; width: 28px; height: 28px; border: none; background: 0 0; border-radius: 4px; cursor: pointer; font-size: 16px; color: var(--he-slate); transition: background .1s; line-height: 1; }
.zoom-btn:hover { background: var(--he-gray-100); }
.zoom-level { min-width: 40px; text-align: center; font-family: var(--he-font-mono); font-size: 12px; color: var(--he-gray-500); }
</style>
</head>
<body>
<div class="zoom-container">
${bodyHtml}
</div>
<script>
(function(){var KEY='he-exp-zoom',zoom=parseFloat(localStorage.getItem(KEY))||1,MIN=.3,MAX=3,STEP=.1;function apply(){var c=document.querySelector('.zoom-container');if(!c)return;c.style.transform='scale('+zoom+')';c.style.transformOrigin='top left';c.style.width=(100/zoom)+'%';var el=document.querySelector('.zoom-level');if(el)el.textContent=Math.round(zoom*100)+'%';try{localStorage.setItem(KEY,zoom)}catch(e){}}var b=document.createElement('div');b.className='zoom-bar';b.innerHTML='<button class="zoom-btn" id="zo">\u2212</button><span class="zoom-level">'+Math.round(zoom*100)+'%</span><button class="zoom-btn" id="zi">+</button><button class="zoom-btn" id="zr">\u27F2</button>';document.body.appendChild(b);document.getElementById('zi').onclick=function(){zoom=Math.min(MAX,zoom+STEP);apply()};document.getElementById('zo').onclick=function(){zoom=Math.max(MIN,zoom-STEP);apply()};document.getElementById('zr').onclick=function(){zoom=1;apply()};document.addEventListener('wheel',function(e){if(!e.ctrlKey&&!e.metaKey)return;e.preventDefault();zoom=Math.max(MIN,Math.min(MAX,zoom-e.deltaY*.002));apply()},{passive:false});document.addEventListener('keydown',function(e){if(!e.ctrlKey&&!e.metaKey)return;if(e.key==='='||e.key==='+'){e.preventDefault();zoom=Math.min(MAX,zoom+STEP);apply()}else if(e.key==='-'){e.preventDefault();zoom=Math.max(MIN,zoom-STEP);apply()}else if(e.key==='0'){e.preventDefault();zoom=1;apply()}});apply()})();
<\/script>
</body>
</html>`;
}
var HEHTMLView = class extends import_obsidian.ItemView {
  constructor(leaf) {
    super(leaf);
    this.file = null;
    this.iframe = null;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return this.file ? this.file.basename : "HTML Preview";
  }
  getIcon() {
    return "eye";
  }
  async setState(state) {
    if (state?.file && typeof state.file === "string") {
      const file = this.app.vault.getFileByPath(state.file);
      if (file)
        await this.setFile(file);
    }
  }
  getState() {
    return { file: this.file?.path };
  }
  async setFile(file) {
    this.file = file;
    await this.loadContent();
  }
  async loadContent() {
    if (!this.file)
      return;
    let content = await this.app.vault.read(this.file);
    const parentPath = this.file.parent ? this.file.parent.path : "";
    content = content.replace(/(src|href)="([^"]+)"/g, (_match, attr, url) => {
      if (url.startsWith("http") || url.startsWith("data") || url.startsWith("app://")) {
        return _match;
      }
      const fullPath = parentPath ? parentPath + "/" + url : url;
      try {
        const resourceUrl = this.app.vault.adapter.getResourcePath(fullPath);
        return attr + '="' + resourceUrl + '"';
      } catch {
        return _match;
      }
    });
    if (!content.includes("zoom-bar")) {
      const zoomHtml = `<style>.zoom-container{transform-origin:top left}.zoom-bar{position:fixed;bottom:24px;right:24px;display:flex;align-items:center;gap:4px;padding:4px 8px;background:var(--he-white,#fff);border:1px solid var(--he-gray-300,#d1cfc5);border-radius:12px;box-shadow:0 4px 10px rgba(20,20,19,.08);z-index:999;user-select:none;opacity:.7;transition:opacity .2s}.zoom-bar:hover{opacity:1}.zoom-btn{display:grid;place-items:center;width:28px;height:28px;border:none;background:0 0;border-radius:4px;cursor:pointer;font-size:16px;color:var(--he-slate,#141413);transition:background .1s;line-height:1}.zoom-btn:hover{background:var(--he-gray-100,#f0eee6)}.zoom-level{min-width:40px;text-align:center;font-family:ui-monospace,monospace;font-size:12px;color:var(--he-gray-500,#87867f)}</style>
<script>(function(){var KEY='he-zoom',zoom=parseFloat(localStorage.getItem(KEY))||1,MIN=.3,MAX=3,STEP=.1;function apply(){var c=document.querySelector('.zoom-container');if(!c)return;c.style.transform='scale('+zoom+')';c.style.transformOrigin='top left';c.style.width=(100/zoom)+'%';var el=document.querySelector('.zoom-level');if(el)el.textContent=Math.round(zoom*100)+'%';try{localStorage.setItem(KEY,zoom)}catch(e){}}if(!document.querySelector('.zoom-bar')){var w=document.createElement('div');w.className='zoom-container';while(document.body.firstChild)w.appendChild(document.body.firstChild);document.body.appendChild(w);var b=document.createElement('div');b.className='zoom-bar';b.innerHTML='<button class="zoom-btn" id="zo">\u2212</button><span class="zoom-level">'+Math.round(zoom*100)+'%</span><button class="zoom-btn" id="zi">+</button><button class="zoom-btn" id="zr">\u27F2</button>';document.body.appendChild(b);document.getElementById('zi').onclick=function(){zoom=Math.min(MAX,zoom+STEP);apply()};document.getElementById('zo').onclick=function(){zoom=Math.max(MIN,zoom-STEP);apply()};document.getElementById('zr').onclick=function(){zoom=1;apply()};document.addEventListener('wheel',function(e){if(!e.ctrlKey&&!e.metaKey)return;e.preventDefault();zoom=Math.max(MIN,Math.min(MAX,zoom-e.deltaY*.002));apply()},{passive:false});document.addEventListener('keydown',function(e){if(!e.ctrlKey&&!e.metaKey)return;if(e.key==='='||e.key==='+'){e.preventDefault();zoom=Math.min(MAX,zoom+STEP);apply()}else if(e.key==='-'){e.preventDefault();zoom=Math.max(MIN,zoom-STEP);apply()}else if(e.key==='0'){e.preventDefault();zoom=1;apply()}});apply()}})();
<\/script>`;
      const bodyEnd = content.lastIndexOf("</body>");
      if (bodyEnd >= 0) {
        content = content.slice(0, bodyEnd) + zoomHtml + content.slice(bodyEnd);
      } else {
        content += zoomHtml;
      }
    }
    const container = this.contentEl;
    container.empty();
    container.addClass("he-htmlview-container");
    this.iframe = container.ownerDocument.createElement("iframe");
    this.iframe.setAttribute("sandbox", "allow-same-origin allow-scripts");
    this.iframe.setAttribute("srcdoc", content);
    this.iframe.className = "he-htmlview-iframe";
    container.appendChild(this.iframe);
  }
  async onOpen() {
  }
  async onClose() {
    this.iframe = null;
    this.file = null;
  }
};
var HEExtPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.views = [];
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE, (leaf) => {
      const view = new HEHTMLView(leaf);
      this.views.push(view);
      return view;
    });
    this.registerExtensions(["html"], VIEW_TYPE);
    this.registerEvent(this.app.workspace.on("file-menu", (menu, file) => {
      if (file instanceof import_obsidian.TFile && file.extension === "html") {
        menu.addItem((item) => {
          item.setTitle("Open with HTML Effectiveness").setIcon("eye").onClick(async () => {
            const leaf = this.app.workspace.getLeaf(true);
            await leaf.setViewState({
              type: VIEW_TYPE,
              state: { file: file.path }
            });
          });
        });
      }
    }));
    this.addCommand({
      id: "open-html-view",
      name: "Open current file in HTML viewer",
      checkCallback: (checking) => {
        const f = this.app.workspace.getActiveFile();
        if (f?.extension === "html") {
          if (!checking) {
            const leaf = this.app.workspace.getLeaf(true);
            void leaf.setViewState({
              type: VIEW_TYPE,
              state: { file: f.path }
            });
          }
          return true;
        }
        return false;
      }
    });
    this.registerEvent(this.app.workspace.on("layout-change", () => {
      this.views = this.views.filter((v) => v.leaf.view !== null);
    }));
    this.registerEvent(this.app.workspace.on("file-open", (file) => {
      if (file && file instanceof import_obsidian.TFile && file.extension === "html") {
        const leaf = this.app.workspace.getLeaf(false);
        if (leaf && leaf.view instanceof HEHTMLView) {
          void leaf.view.setFile(file);
        }
      }
    }));
    this.registerEvent(this.app.vault.on("modify", (file) => {
      if (file instanceof import_obsidian.TFile && file.extension === "html") {
        for (const view of this.views) {
          if (view.file?.path === file.path) {
            void view.setFile(file);
          }
        }
      }
    }));
    this.registerMarkdownCodeBlockProcessor("html-effect", (src, el, ctx) => {
      processor(src, el, ctx, this.settings.defaultTheme);
    });
    this.addCommand({ id: "export-note", name: "Export note as HTML", callback: () => exportNoteAsHTML(this.app, this) });
    this.addCommand({ id: "compare", name: "Compare", editorCallback: (e) => e.replaceSelection("```html-effect\ncompare\n\nLeft\n---\nRight\n```") });
    this.addCommand({ id: "timeline", name: "Timeline", editorCallback: (e) => e.replaceSelection("```html-effect\ntimeline\n\n- [2026-01] Event\n- [2026-06] Another\n```") });
    this.addCommand({ id: "report", name: "Report", editorCallback: (e) => e.replaceSelection("```html-effect\n---\ntype: report\n---\n## \n- 85%: Rate\n\n# Title\nContent\n```") });
    this.addCommand({ id: "slides", name: "Slides", editorCallback: (e) => e.replaceSelection("```html-effect\nslides\n\n# One\nContent\n---\n# Two\nContent\n```") });
    this.addCommand({ id: "diagram", name: "Diagram", editorCallback: (e) => e.replaceSelection("```html-effect\ndiagram\n\n\xE2\x94\x8C\xE2\x94\x80\xE2\x94\x80\xE2\x94\x80\xE2\x94\x90\n\xE2\x94\x82App\xE2\x94\x82\n\xE2\x94\x94\xE2\x94\xAC\xE2\x94\x80\xE2\x94\x98\n  \xE2\x96\xBC\n\xE2\x94\x8C\xE2\x94\x80\xE2\x94\x80\xE2\x94\x90\n\xE2\x94\x82DB\xE2\x94\x82\n\xE2\x94\x94\xE2\x94\x80\xE2\x94\x80\xE2\x94\x98\n```") });
    this.addSettingTab(new HESettingTab(this.app, this));
  }
  async loadSettings() {
    const data = await this.loadData();
    if (data) {
      if (data.defaultTheme === "light")
        this.settings.defaultTheme = "light";
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var HESettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Display").setHeading();
    new import_obsidian.Setting(containerEl).setName("Default theme").setDesc("Theme for rendered blocks").addDropdown((d) => d.addOption("dark", "Dark").addOption("light", "Light").setValue(this.plugin.settings.defaultTheme).onChange(async (v) => {
      this.plugin.settings.defaultTheme = v;
      await this.plugin.saveSettings();
    }));
  }
};
